refactor(nixago): moves optional nixago configs to presets cell
divnix/std pull request #129
Opened 2022-09-10 15:38 UTC by jmgilman

Fixes #128.

2022-09-10 15:44 UTC, jmgilman commented
The *.md files for the Nixago configs seem redundant with the [documentation already provided for them](https://divnix.github.io/std/reference/std/nixago/index.html). Can we consider removing these? It cleans up the directory and makes it easier to find the *.nix files.

2022-09-10 15:52 UTC, jmgilman commented
One other thing. With the way [this is setup](https://github.com/divnix/std/blob/3335a48d421604093e5e48527e870973d9735511/cells/std/lib/default.nix#L47-L52), we have to do [things like this](https://github.com/divnix/std/blob/main/cells/std/nixago.nix#L61). I wonder if we just consider making `config` optional here is well? It would reduce a bit of boilerplate.

2022-09-10 16:18 UTC, blaggacao requested changes
`mdbook.hook.extra` in `cells/std/nixago.nix` appears to still consume a contract from the now moved `cells/std/nixago/mdbook.nix`

2022-09-10 16:18 UTC, blaggacao commented on cells/presets/nixago.nix
> +    output = ".conform.yaml";
Is this copying over on purpose? If so, I'm not sure I understand why here and not with the others. I'd expect _not_ to redefine it here.

2022-09-10 16:21 UTC, blaggacao commented
> The *.md files for the Nixago configs seem redundant with the documentation already provided for them. 

These are symlinks. In their current place, these docs are also rendered inside the TUI, when you type`?`.

We should likely just leave them here, since they do little more than link to the tools with a one-liner decsription.

2022-09-10 16:26 UTC, blaggacao commented
> I wonder if we just consider making config optional here is well? It would reduce a bit of boilerplate.

Since this is sort of boilerplate within boilerplate, I think it actually conveys a bit of information, namely that it's not _actually_ optional. Well, technically, it is, but one would end up with an empty file.

So once one is actually looking at the boilerplate, one can still draw value of it.

So I'd leave it as it is, here.

2022-09-11 02:21 UTC, blaggacao commented
Thanks a lot for this cleanup. :rocket: :+1:  I just rebased and merged into master here: https://github.com/divnix/std/commit/bff0e737b872af59ba70fdf6e06b7dc212156d17

closing.

2022-09-11 02:21 UTC, closed without merging